package render_test

import (
	"testing"

	"github.com/GyeongHoKim/gerrit-mcp-server/internal/gerrit"
	"github.com/GyeongHoKim/gerrit-mcp-server/internal/render"
)

func sampleMessages(t *testing.T) []gerrit.ChangeMessage {
	t.Helper()

	return []gerrit.ChangeMessage{
		{
			ID: "m1", Message: "Uploaded patch set 1.", RevisionNumber: 1,
			Date:   at(t, "2026-07-30 09:00:00.000000000"),
			Author: &gerrit.AccountInfo{Name: "Alice Adams", AccountID: 1},
		},
		{
			ID: "m2", Message: "Patch Set 1: Verified+1\n\nBuild Successful", RevisionNumber: 1,
			Tag:    "autogenerated:jenkins",
			Date:   at(t, "2026-07-30 09:05:00.000000000"),
			Author: &gerrit.AccountInfo{Name: "Jenkins", AccountID: 99},
		},
		{
			ID: "m3", Message: "Patch Set 1: Code-Review+2\n\nlooks good", RevisionNumber: 1,
			Date:   at(t, "2026-07-30 10:00:00.000000000"),
			Author: &gerrit.AccountInfo{Name: "Carol Chen", AccountID: 3},
		},
		// A system message: no author, no patch set.
		{
			ID: "m4", Message: "Change has been successfully merged",
			Date: at(t, "2026-07-30 11:00:00.000000000"),
		},
	}
}

func TestMessages(t *testing.T) {
	t.Parallel()

	t.Run("messages_none", func(t *testing.T) {
		t.Parallel()

		golden(t, "messages_none", render.Messages(nil))
	})

	t.Run("messages_mixed", func(t *testing.T) {
		t.Parallel()

		golden(t, "messages_mixed", render.Messages(sampleMessages(t)))
	})

	// Gerrit 3.x hands the body over with accounts replaced by placeholders
	// and the names in a side list. A placeholder with no entry is left as it
	// came rather than dropped: a wrong token beats a silently missing name.
	t.Run("messages_accounts", func(t *testing.T) {
		t.Parallel()

		golden(t, "messages_accounts", render.Messages([]gerrit.ChangeMessage{{
			ID: "m3", Message: "<GERRIT_ACCOUNT_2> and <GERRIT_ACCOUNT_7> looked at this", RevisionNumber: 1,
			Date:              at(t, "2026-07-30 10:00:00.000000000"),
			Author:            &gerrit.AccountInfo{Name: "Carol Chen", AccountID: 3},
			AccountsInMessage: []gerrit.AccountInfo{{Name: "Bob Brown", AccountID: 2}},
		}}))
	})
}

// The renderer must not depend on anything that varies between calls.
func TestMessagesIsDeterministic(t *testing.T) {
	t.Parallel()

	first := render.Messages(sampleMessages(t))

	for i := range 20 {
		if got := render.Messages(sampleMessages(t)); got != first {
			t.Fatalf("run %d differs from the first:\n%s", i, got)
		}
	}
}
