package gerrit

import (
	"errors"
	"net/http"
	"testing"
)

const messagesBody = `[
  {"id": "m1", "date": "2026-07-30 09:00:00.000000000", "_revision_number": 1,
   "message": "Uploaded patch set 1.",
   "author": {"_account_id": 1, "name": "Alice Adams"}},
  {"id": "m2", "date": "2026-07-30 09:05:00.000000000", "_revision_number": 1,
   "tag": "autogenerated:jenkins",
   "message": "Patch Set 1: Verified+1\n\nBuild Successful",
   "author": {"_account_id": 99, "name": "Jenkins"}},
  {"id": "m3", "date": "2026-07-30 10:00:00.000000000", "_revision_number": 1,
   "message": "Patch Set 1: Code-Review+2\n\n<GERRIT_ACCOUNT_2> looks good",
   "author": {"_account_id": 3, "name": "Carol Chen"},
   "accounts_in_message": [{"_account_id": 2, "name": "Bob Brown"}]},
  {"id": "m4", "date": "2026-07-30 11:00:00.000000000",
   "message": "Change has been successfully merged"}
]`

func TestListChangeMessages(t *testing.T) {
	t.Parallel()

	var gotPath string

	client := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.EscapedPath()

		if _, err := w.Write([]byte(xssiPrefix + "\n" + messagesBody)); err != nil {
			t.Errorf("writing test response: %v", err)
		}
	})

	got, err := client.ListChangeMessages(t.Context(), "12345")
	if err != nil {
		t.Fatalf("ListChangeMessages() returned an unexpected error: %v", err)
	}

	if want := "/a/changes/12345/messages"; gotPath != want {
		t.Errorf("path = %q, want %q", gotPath, want)
	}

	if len(got) != 4 {
		t.Fatalf("len(messages) = %d, want 4", len(got))
	}

	// Server order is chronological; nothing here may reorder it.
	if got[0].ID != "m1" || got[3].ID != "m4" {
		t.Errorf("ids = %q, %q, want m1 first and m4 last", got[0].ID, got[3].ID)
	}

	if got[1].Tag != "autogenerated:jenkins" {
		t.Errorf("Tag = %q, want the autogenerated tag kept", got[1].Tag)
	}

	if got[0].RevisionNumber != 1 {
		t.Errorf("RevisionNumber = %d, want 1", got[0].RevisionNumber)
	}

	if got[0].Date.IsZero() {
		t.Error("Date is zero, want it parsed from Gerrit's layout")
	}

	// The placeholder in the body is only useful with the list that resolves it.
	if len(got[2].AccountsInMessage) != 1 || got[2].AccountsInMessage[0].Name != "Bob Brown" {
		t.Errorf("AccountsInMessage = %+v, want Bob Brown", got[2].AccountsInMessage)
	}

	// A system message has no author and no patch set; neither is an error.
	if got[3].Author != nil {
		t.Errorf("Author = %+v, want nil on a system message", got[3].Author)
	}

	if got[3].RevisionNumber != 0 {
		t.Errorf("RevisionNumber = %d, want 0 when absent", got[3].RevisionNumber)
	}
}

func TestListChangeMessagesEmpty(t *testing.T) {
	t.Parallel()

	client := newTestClient(t, func(w http.ResponseWriter, _ *http.Request) {
		if _, err := w.Write([]byte(xssiPrefix + "\n[]")); err != nil {
			t.Errorf("writing test response: %v", err)
		}
	})

	got, err := client.ListChangeMessages(t.Context(), "12345")
	if err != nil {
		t.Fatalf("ListChangeMessages() returned an unexpected error: %v", err)
	}

	if len(got) != 0 {
		t.Errorf("len(messages) = %d, want 0", len(got))
	}
}

func TestListChangeMessagesEscapesTheTriplet(t *testing.T) {
	t.Parallel()

	var gotPath string

	client := newTestClient(t, func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.EscapedPath()

		if _, err := w.Write([]byte(xssiPrefix + "\n[]")); err != nil {
			t.Errorf("writing test response: %v", err)
		}
	})

	if _, err := client.ListChangeMessages(t.Context(), "a/b~main~I1"); err != nil {
		t.Fatalf("ListChangeMessages() returned an unexpected error: %v", err)
	}

	if want := "/a/changes/a%2Fb~main~I1/messages"; gotPath != want {
		t.Errorf("path = %q, want %q", gotPath, want)
	}
}

func TestListChangeMessagesRejectsEmptyID(t *testing.T) {
	t.Parallel()

	client := newTestClient(t, func(_ http.ResponseWriter, _ *http.Request) {
		t.Error("ListChangeMessages() reached the server, want it to refuse before that")
	})

	if _, err := client.ListChangeMessages(t.Context(), " "); !errors.Is(err, ErrEmptyChangeID) {
		t.Errorf("ListChangeMessages() error = %v, want ErrEmptyChangeID", err)
	}
}

func TestListChangeMessagesReportsNotFound(t *testing.T) {
	t.Parallel()

	client := newTestClient(t, func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusNotFound)
	})

	if _, err := client.ListChangeMessages(t.Context(), "12345"); !errors.Is(err, ErrNotFound) {
		t.Errorf("ListChangeMessages() error = %v, want ErrNotFound", err)
	}
}
