package gerrit

import (
	"context"
	"net/http"
	"strings"
)

// ChangeMessage is one entry in a change's log: a patch set uploaded, a vote
// cast, a review posted, a build reported.
type ChangeMessage struct {
	// Author wrote the message. Nil when the Gerrit system did.
	Author *AccountInfo `json:"author,omitempty"`
	// Date is when the message was posted.
	Date Timestamp `json:"date"`
	// Message is the text.
	Message string `json:"message,omitempty"`
	// ID identifies the message.
	ID string `json:"id"`
	// Tag marks the origin. Automated messages carry an "autogenerated:"
	// prefix; it is kept so a reader can tell a bot from a person.
	Tag string `json:"tag,omitempty"`
	// AccountsInMessage resolves the <GERRIT_ACCOUNT_N> placeholders that
	// Gerrit 3.x writes into Message in place of names.
	AccountsInMessage []AccountInfo `json:"accounts_in_message,omitempty"`
	// RevisionNumber is the patch set the message belongs to, 0 when none.
	RevisionNumber int `json:"_revision_number,omitempty"`
}

// ListChangeMessages retrieves every message on a change, oldest first.
//
// Everything is returned, automated messages included: a build result in the
// log is exactly what an agent asking "has anyone reacted to this?" needs.
func (c *Client) ListChangeMessages(ctx context.Context, changeID string) ([]ChangeMessage, error) {
	changeID = strings.TrimSpace(changeID)
	if changeID == "" {
		return nil, ErrEmptyChangeID
	}

	var messages []ChangeMessage
	if err := c.do(ctx, http.MethodGet, changePath(changeID, "/messages"), nil, nil, &messages); err != nil {
		return nil, err
	}

	return messages, nil
}
